name: CanopyClaimTeleport
main: com.canopymc.claim_teleport.CTMain
version: 2.0.0
authors: [TheMrJezza, Albert]
softdepend: [GriefPrevention]
commands:
  claimteleport:
    description: Teleport to a Claim
      usage: /<command>
      aliases: [ctp, claimtp]
  ctpreload:
    description: Reload Plugin Config
permissions:
  ctp.reload:
    default: op
  ctp.use:
    default: op