# ==================================================================== 
#   ______   _          __     ___   __   __        _______   ______
#  [ _____] [ ]       _[__]_  [_ _] [  ]_[  ]      [__   __] [ ____ ]
#  [ ]      [ ]      [ ]__[ ]  [ ]  [ ][_][ ]         [ ]    [ ]__[ ]
#  [ ]____  [ ]____  [ ____ ]  [ ]  [ ]   [ ]         [ ]    [ _____]
#  [______] [______] [_]  [_] [___] [_]   [_]         [_]    [_]
# 
# ====================================================================

#
#
#
Messages:
  AboutToTeleport: "&ADon't Move! You will be teleported in &e{DELAY} &aseconds!"
  TeleportSuccess: "&aTeleporting..."
  Teleporting: "&cTelepot in %s% seconds, please do not move..."
  PlayerMoved: "&cYou moved teleport canceled!"
  NoPermission: "&cYou dont have permission!"
  InvalidClaimID: "&cInvalid ClaimID"
  NotNumeric: "&cPlease insert valid numbers!"
  NullInput: "&cWrong command usage"
  InvalidPlayer: "&cPlayer not found!"
#
# 
EnableSound: true

# The Teleport Delay (Or Countdown) is used to delay the teleport.
TeleportDelay:
  #
  # How long should the delay be, in seconds? Set to 0 or lower to disable.
  TimeInSeconds: 3.5
  #
  # Should the teleport be cancelled if the player moves?
  CancelOnMove: true